# NOTICE: If you are familiar with the python eco system you may ignore this file
# Otherwise, it offers some minimal workflow automation using https://taskfile.dev/
version: '3'
vars:
  # Put this in the root of the repo for vscode autodection
  VENV_DIR: venv
  PACKAGE_NAME: datatrails_scitt_samples

tasks:

  install:dev:
    desc: Install the package in development mode (in the virtual environment)
    deps:
      - task: venv
    cmds:
      - |
        set -e
        source {{.VENV_DIR}}/bin/activate
        python -m pip install -e .

  audit:
    desc: Audit the code
    deps:
      - task: venv
    cmds:
      - |
        set -e
        source {{.VENV_DIR}}/bin/activate

        pip-audit -r requirements.txt
        
        deactivate

  check:
    desc: Check the style, bug and quality of the code
    deps:
      - task: venv
    cmds:
      - |
        set -e
        source {{.VENV_DIR}}/bin/activate

        python3 --version
        ruff check {{ .PACKAGE_NAME }} unittests
        python3 -m pyright --stats {{ .PACKAGE_NAME }} unittests
        
        deactivate

  clean:
    desc: Clean git repo
    cmds:
      - find -name '*,cover' -type f -delete
      - git clean -fdX

  format:
    desc: Format code using black
    deps:
      - task: venv
    cmds:
      - |
        set -e
        source {{ .VENV_DIR }}/bin/activate

        ruff check --fix {{ .PACKAGE_NAME }} unittests
        black {{ .PACKAGE_NAME }} unittests
        
        deactivate

  test:
    desc: Run unittests
    deps:
      - task: venv
    cmds:
      - |
        set -e
        source {{ .VENV_DIR }}/bin/activate

        python3 -m unittest
        
        deactivate

  test:wheel:
    desc: |
      Build and install the package, then register a signed statement with the datatrails server

      ** REQUIRES ENVIRONMENT VARIABLES **
      DATATRAILS_URL
      DATATRAILS_CLIENT_ID
      DATATRAILS_CLIENT_SECRET

      Add them to .env.token for maximal convenience
    deps:
      - task: wheel
    cmds:
      - pip install --force-reinstall dist/*.whl
      - task: registration-demo


  registration-demo:
    envfile: .env.token
    desc: |
      Build and install the package, then register a signed statement with the datatrails server

      ** REQUIRES ENVIRONMENT VARIABLES **
      DATATRAILS_URL
      DATATRAILS_CLIENT_ID
      DATATRAILS_CLIENT_SECRET

      Add them to .env.token for maximal convenience

    vars:
      PAYLOAD: '{\"name\": \"R2D2\"}'
      CONTENT_TYPE: "application/json"
      SUBJECT: "test:wheel"
      ISSUER: "github.com/datatrails/datatrails-scitt-samples/Taskfile.yml"

    cmds:
      - |
        set -e
        source {{ .VENV_DIR }}/bin/activate

        echo "Generating ephemeral issuer key"
        datatrails-sciit-demo-generate-example-key \
          --signing-key-file datatrails_scitt_samples-signing-key.pem

        echo "Creating the statement"
        echo {{ .PAYLOAD }} > payload.json
        create-signed-statement \
            --signing-key-file datatrails_scitt_samples-signing-key.pem \
            --payload-file payload.json \
            --content-type {{ .CONTENT_TYPE }} \
            --subject {{ .SUBJECT }} \
            --issuer {{ .ISSUER }} \
            --output-file signed-statement.cbor

        echo "Registering the statement"
        register-signed-statement \
            --signed-statement-file signed-statement.cbor \
            --output-file transparent-statement.cbor \
            --output-receipt-file statement-receipt.cbor

        echo "The statement has been registered, and its receipt fully verified"

        echo -n "Transparent Statement: "
        cat transparent-statement.cbor | base64
        echo -n "Receipt              : "
        cat statement-receipt.cbor | base64

        deactivate


  venv:
    desc: Builds python environment
    cmds: 
      - |
        set -e
        if [ ! -d {{ .VENV_DIR }} ]
        then
            python3 -m venv {{ .VENV_DIR }}
            source {{ .VENV_DIR }}/bin/activate
            python3 -m pip install -qq -r requirements.txt
            python3 -m pip install -qq -r requirements-dev.txt
            deactivate
        fi

  wheel:
    desc: Builds python wheel package
    deps:
      - task: venv
    cmds:
      - |
        set -e
        rm -rf dist/*
        source {{ .VENV_DIR }}/bin/activate
        python3 -m build --sdist
        python3 -m build --wheel
        twine check dist/*
        
        deactivate

