# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Quality Control

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12" ]
        # reduced matrix for ci
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements-dev.txt
      shell: bash
    - name: Run integrity checks
      run: |
        pycodestyle --format=pylint scitt unittests
        python3 -m pylint scitt unittests
        black scitt unittests
        modified=$(git status -s | wc -l)
        if [ $modified -gt 0 ]
        then
            echo "there are $modified files that must be reformatted"
            exit 1
        fi
        python3 -m unittest
      shell: bash
    - name: Run type-hint checks
      if: ${{ matrix.python-version != '3.12' }}
      run: |
        python3 -m pyright --stats scitt
      shell: bash
    - uses: pypa/gh-action-pip-audit@v1.0.8
      if: ${{ matrix.os == 'ubuntu-latest' }}
      with:
        # GHSA-wj6h-64fc-37mp - python-ecdsa will not be fixed by maintainers
        ignore-vulns: |
          GHSA-wj6h-64fc-37mp
        inputs: requirements.txt


