name: hello

on:
  workflow_dispatch:

jobs:
  register-statement:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: hello
      run: echo "Hello, World!"

