name: hello

on:
  workflow_dispatch:
  # push:
    # branches: [ "main" ]

jobs:
  register-statement:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: hello
        run: |
          echo "Hello, World!"