# This workflow tests that the installed package and its scripts work as expectedca
# It is a pre-requisite for publishing a releasew wheel to PyPI

name: Package and Publish

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: "3.x"
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
        python3 -m pip install -r requirements-dev.txt
      shell: bash

    - name: Create wheel
      run: |
         python3 -m build --sdist
         python3 -m build --wheel
      shell: bash

    - name: Test installed package (registration-demo)
      env:
        DATATRAILS_URL: ${{ vars.DATATRAILS_URL }}
        DATATRAILS_CLIENT_ID: ${{ vars.DATATRAILS_CLIENT_ID }}
        DATATRAILS_CLIENT_SECRET: ${{ secrets.DATATRAILS_CLIENT_SECRET }}

      run: |
        python3 -m pip install --force-reinstall dist/*.whl
        task registration-demo
      shell: bash

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
        attestations: false
        # skip-existing: true
        user: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets.PYPI_PASSWORD }}
