name: Registration Demo

# NOTE: This workflow can't be tested until it is merged into the main branch :-/

on:
  workflow_dispatch:
    inputs:
      subject:
        description: 'Statement subject'
        default: "demo subject"
      issuer:
        description: 'Statement subject'
        default: "github.com/datatrails/datatrails-scitt-samples"
      payload:
        description: 'Statement payload'
        default: "{\"name\": \"R2D2\"}"
      content_type:
        description: 'Statement content type'
        default: "application/json"

env:
  DATATRAILS_CLIENT_SECRET: ${{ secrets.DATATRAILS_CLIENT_SECRET }}

jobs:
  register-statement:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements-dev.txt
        shell: bash
      - name: Generate ephemeral issuer key
        run: |
          python3 -m datatrails_scitt_samples.scripts.generate_example_key.py \
            --signing-key-file-path datatrails_scitt_samples-signing-key.pem

      - name: Create statement
        run: |

          # NOTE: We are reling on github's ui to sanitize the inputs

          echo ${{ inputs.payload }} > /tmp/payload.json
          python3 -m datatrails_scitt_samples.scripts.create_signed_statement \
            --signing-key-file-path datatrails_scitt_samples-signing-key.pem \
            --payload-file /tmp/payload.json \
            --content-type ${{ inputs.content_type }} \
            --subject ${{ inputs.subject }} \
            --issuer ${{ inputs.issuer }} \
            --output-file signed-statement.cbor

      - name: Register statement
        env:
          DATATRAILS_URL: ${{ vars.DATATRAILS_URL }}
          DATATRAILS_CLIENT_ID: ${{ vars.DATATRAILS_CLIENT_ID }}
          DATATRAILS_CLIENT_SECRET: ${{ secrets.DATATRAILS_CLIENT_ID }}

        run: |

          python3 -m datatrails_scitt_samples.scripts.register_signed_statement \
            --signed-statement-file signed-statement.cbor \
            --output-file transparent-statement.cbor \
            --output-receipt-file statement-receipt.cbor

          echo -n "Transparent Statement: "
          cat transparent-statement.cbor | base64
          echo -n "Receipt              : "
          cat statement-receipt.cbor | base64