name: Registration Demo

on:
  workflow_dispatch:
    inputs:
      subject:
        description: 'Statement subject'
        default: "demo subject"
      issuer:
        description: 'Statement subject'
        default: "github.com/datatrails/datatrails-scitt-samples"
      payload:
        description: 'Statement payload'
        default: "{\"name\": \"R2D2\"}"
      content_type:
        description: 'Statement content type'
        default: "application/json"

env:
  DATATRAILS_CLIENT_SECRET: ${{ secrets.DATATRAILS_CLIENT_SECRET }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12" ]
        # reduced matrix for ci
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements-dev.txt
      shell: bash
    - name: Generate ephemeral issuer key
      run: |
        python3 -m scitt.scripts.generate_example_key.py \
          --signing-key-file-path scitt-signing-key.pem

    - name: Create statement
      run: |
        export DATATRAILS_URL=${{ env.DATATRAILS_URL }}
        export DATATRAILS_CLIENT_ID=${{ env.DATATRAILS_CLIENT_ID }}
        export DATATRAILS_CLIENT_SECRET=${{ secrets.DATATRAILS_CLIENT_ID }}

        echo ${{ inputs.payload }} > payload.json
        python3 -m scitt.scripts.create_signed_statement \
          --signing-key-file-path scitt-signing-key.pem \
          --payload-file payload.json \
          --content-type ${{ inputs.content_type }} \
          --subject ${{ inputs.subject }} \
          --issuer ${{ inputs.issuer }} \
          --output-file signed-statement.cbor

    - name: Register statement
      run: |
        export DATATRAILS_URL=${{ env.DATATRAILS_URL }}
        export DATATRAILS_CLIENT_ID=${{ env.DATATRAILS_CLIENT_ID }}
        export DATATRAILS_CLIENT_SECRET=${{ secrets.DATATRAILS_CLIENT_ID }}

        python3 -m scitt.scripts.register_signed_statement \
          --signed-statement-file signed-statement.cbor \
          --output-file transparent-statement.cbor \
          --output-receipt-file statement-receipt.cbor

        echo -n "Transparent Statement: "
        cat transparent-statement.cbor | base64
        echo -n "Receipt              : "
        cat statement-receipt.cbor | base64